language: python
dist: bionic
python:
  - "3.8"

notifications:
  email: false

before_install:
  - sudo apt-get update

install:
  - pip install coverage
  - pip install .

script:
  - coverage run -m unittest gym_art/quadrotor_multi/tests/test_multi_env.py

after_success:
  - bash <(curl -s https://codecov.io/bash)